"""Shared task status definitions."""

from __future__ import annotations

TASK_STATUSES = (
    "CREATED",
    "QUEUED",
    "DISPATCHED",
    "EXECUTING",
    "COMPLETED",
    "TIMEOUT",
    "ERROR",
    "ABANDONED",
)

TERMINAL_TASK_STATUSES = frozenset(("COMPLETED", "TIMEOUT", "ERROR", "ABANDONED"))
NONTERMINAL_TASK_STATUSES = ("CREATED", "QUEUED", "DISPATCHED", "EXECUTING")
COMPLETABLE_TASK_STATUSES = ("QUEUED", "DISPATCHED", "EXECUTING")
ACTIVE_TARGET_TASK_STATUSES = ("DISPATCHED", "EXECUTING")
